"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {ArrowDown,ArrowRight,ArrowUp,Languages,Moon,RefreshCw,Sun} from "lucide-react";
import type {AssetSnapshot,DashboardSnapshot} from "@/lib/types";
import {distance} from "@/lib/analytics/engine";
import MarketChart from "@/components/market-chart";

type Lang="ar"|"en"; type Poll="off"|"10"|"30"|"60"|"300";
type H={timestamp:string;symbol:string;price:number|null;action:string;oi:number|null;volume:number|null};

const ar:any={title:"MARKET INTELLIGENCE",sub:"لوحة ذكاء السوق اللحظية",overview:"نظرة السوق",hourly:"📊 التحليل الساعي",derivatives:"عقود BTC / ETH",bmnr:"🚨 BMNRB",bmnu:"BMNU",semi:"🧠 SEMICONDUCTOR PULSE",pair:"SOXL / SOXS",changes:"🔄 منذ الساعة السابقة",important:"🎯 أهم النقاط المباشرة للتداول",signals:"🚦 إشارات التغيير",indicators:"⚙️ المؤشرات",refresh:"تحديث",session:"جلسة السوق",asset:"الأصل",price:"السعر",market:"الجلسة",direction:"الاتجاه",confidence:"Confidence",support:"الدعم",down:"Downside %",resistance:"المقاومة",up:"Upside %",entry:"Entry",tp:"TP",stop:"Stop",risk:"Risk",news:"News",action:"Action",pivot:"Pivot",trigger:"Trigger",target:"Target",invalid:"Invalidation",provider:"المصدر",fresh:"العمر",previous:"السابق",current:"الحالي",delta:"Δ%",prevAction:"Action السابق",curAction:"Action الحالي",keyChange:"التغيير الأهم",noHistory:"لا توجد عينة سابقة",footer:"المستويات والمؤشرات سيناريوهات فنية وليست ضمانًا أو توصية استثمارية شخصية.",distanceNote:"النسب تمثل المسافة إلى المستوى الفني وليست احتمالاً.",breadth:"اتساع القطاع",sectorBias:"ميل القطاع",vwap:"VWAP",dayLow:"أدنى اليوم",oi:"OI",doi:"ΔOI",taker:"Taker Ratio",funding:"Funding",volume:"Volume",high:"High",low:"Low",bid:"Bid",ask:"Ask",spread:"Spread",imbalance:"Order-book imbalance",trades:"Trades"};
const en:any={title:"MARKET INTELLIGENCE",sub:"Intraday market intelligence dashboard",overview:"Market overview",hourly:"📊 Hourly analysis",derivatives:"BTC / ETH Futures",bmnr:"🚨 BMNRB",bmnu:"BMNU",semi:"🧠 SEMICONDUCTOR PULSE",pair:"SOXL / SOXS",changes:"🔄 Since previous hour",important:"🎯 Most important trading levels",signals:"🚦 Change signals",indicators:"⚙️ Indicators",refresh:"Refresh",session:"Market session",asset:"Asset",price:"Price",market:"Session",direction:"Direction",confidence:"Confidence",support:"Support",down:"Downside %",resistance:"Resistance",up:"Upside %",entry:"Entry",tp:"TP",stop:"Stop",risk:"Risk",news:"News",action:"Action",pivot:"Pivot",trigger:"Trigger",target:"Target",invalid:"Invalidation",provider:"Provider",fresh:"Age",previous:"Previous",current:"Current",delta:"Δ%",prevAction:"Previous Action",curAction:"Current Action",keyChange:"Key Change",noHistory:"No previous sample",footer:"Levels and indicators are technical scenarios, not guarantees or personalized investment advice.",distanceNote:"Percentages are distance to technical levels, not probabilities.",breadth:"Breadth",sectorBias:"Sector bias",vwap:"VWAP",dayLow:"Day low",oi:"OI",doi:"ΔOI",taker:"Taker Ratio",funding:"Funding",volume:"Volume",high:"High",low:"Low",bid:"Bid",ask:"Ask",spread:"Spread",imbalance:"Order-book imbalance",trades:"Trades"};

function fmt(v:number|null|undefined,p=false){if(v==null||!Number.isFinite(v))return"—";return p?(v>=0?"+":"")+v.toFixed(2)+"%":new Intl.NumberFormat("en-US",{maximumFractionDigits:Math.abs(v)>=1000?2:4}).format(v)}
function age(ts:string|null){if(!ts)return"—";const s=Math.max(0,Math.floor((Date.now()-Date.parse(ts))/1000));return s<60?s+"s":s<3600?Math.floor(s/60)+"m":Math.floor(s/3600)+"h"}
function ac(a:string){return a==="BUY BIAS"?"good":a==="SELL/AVOID"?"bad":"wait"} function sc(s:string){return ["LIVE","IEX","REGULAR"].includes(s)?"good":["DELAYED","PRE-MARKET","AFTER-HOURS"].includes(s)?"wait":["STALE","DEGRADED","DATA UNAVAILABLE"].includes(s)?"bad":"muted"}
function icon(d:string){return d==="UP"?<ArrowUp size={14}/>:d==="DOWN"?<ArrowDown size={14}/>:<ArrowRight size={14}/>}
function Spark({a}:{a:AssetSnapshot}){const b=a.quote.bars?.slice(-28)||[];if(b.length<2)return <div className="h-8"/>;const v=b.map(x=>x.close),mn=Math.min(...v),mx=Math.max(...v),sp=Math.max(mx-mn,1e-9),pts=v.map((x,i)=>(i/(v.length-1)*100)+","+(28-(x-mn)/sp*24)).join(" ");return <svg viewBox="0 0 100 30" className="h-8 w-full"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>}
function Badge({a}:{a:string}){return <span className={"rounded-md border border-current/20 px-2 py-1 text-[9px] font-black "+ac(a)}>{a}</span>}
function S({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-4"><h2 className="mb-2 text-[12px] font-black">{title}</h2>{children}</section>}

export default function Dashboard(){
 const [lang,setLang]=useState<Lang>("ar"),[theme,setTheme]=useState<"dark"|"light">("dark"),[poll,setPoll]=useState<Poll>("30"),[snap,setSnap]=useState<DashboardSnapshot|null>(null),[loading,setLoading]=useState(false),[hist,setHist]=useState<H[]>([]);const t=lang==="ar"?ar:en;
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/market/snapshot",{cache:"no-store"});if(r.ok)setSnap(await r.json())}finally{setLoading(false)}},[]);
 useEffect(()=>{setLang((localStorage.getItem("mid_lang") as Lang)||"ar");setTheme((localStorage.getItem("mid_theme") as any)||"dark");try{setHist(JSON.parse(localStorage.getItem("mid_history")||"[]"))}catch{};load()},[load]);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.documentElement.classList.toggle("light",theme==="light");localStorage.setItem("mid_lang",lang);localStorage.setItem("mid_theme",theme)},[lang,theme]);
 useEffect(()=>{if(poll==="off")return;let id:any;const go=()=>{clearInterval(id);if(!document.hidden)id=setInterval(load,Number(poll)*1000)};go();document.addEventListener("visibilitychange",go);return()=>{clearInterval(id);document.removeEventListener("visibilitychange",go)}},[poll,load]);
 useEffect(()=>{if(!snap)return;const d=new Date(snap.generatedAt);d.setMinutes(0,0,0);const k=d.toISOString(),rows=snap.assets.map(a=>({timestamp:k,symbol:a.symbol,price:a.quote.price,action:a.technical.action,oi:a.derivatives?.openInterest||null,volume:a.quote.volume}));setHist(p=>{const n=[...p.filter(x=>x.timestamp!==k),...rows].slice(-144);localStorage.setItem("mid_history",JSON.stringify(n));return n})},[snap]);
 const prev=useMemo(()=>{const m=new Map<string,H>();if(!snap)return m;const d=new Date(snap.generatedAt);d.setMinutes(0,0,0);const k=new Date(d.getTime()-3600000).toISOString();hist.filter(x=>x.timestamp===k).forEach(x=>m.set(x.symbol,x));return m},[snap,hist]);
 const bm=snap?.assets.find(a=>a.symbol==="BMNRB"),bmnu=snap?.assets.find(a=>a.symbol==="BMNU"),soxl=snap?.assets.find(a=>a.symbol==="SOXL"),soxs=snap?.assets.find(a=>a.symbol==="SOXS"),ctx=snap?.contextAssets||[];const up=ctx.filter(a=>(a.quote.change24h||0)>0).length,dn=ctx.filter(a=>(a.quote.change24h||0)<0).length,bias=ctx.length<3?"—":up>=4?"STRONG":dn>=4?"WEAK":"MIXED";
 const alerts=snap?.assets.flatMap(a=>{const p=a.quote.price,x=a.technical;if(p==null)return[];if(x.breakoutTrigger!=null&&p>=x.breakoutTrigger)return[a.label+" · 🚀 BREAKOUT "+fmt(x.breakoutTrigger)];if(x.breakdownTrigger!=null&&p<=x.breakdownTrigger)return[a.label+" · ⚠️ SUPPORT LOST "+fmt(x.breakdownTrigger)];if(x.pivot!=null&&Math.abs(p-x.pivot)/p<.002)return[a.label+" · 🟡 PIVOT TEST "+fmt(x.pivot)];return[]})||[];
 return <main className="mx-auto max-w-[1600px] p-3 md:p-4">
  <header className="panel sticky top-0 z-20 rounded-xl p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-lg font-black">{t.title}</div><div className="muted text-[10px]">{t.sub}</div></div><div className="flex flex-wrap items-center gap-2 text-[10px]"><span className="subpanel rounded-lg px-2 py-1.5 num">🇸🇦 {snap?.saudiTime||"—"}</span><span className="subpanel rounded-lg px-2 py-1.5">{t.session}: <b>{snap?.usSession||"—"}</b></span><button onClick={load} className="subpanel flex items-center gap-1 rounded-lg px-2 py-1.5"><RefreshCw size={12} className={loading?"animate-spin":""}/>{t.refresh}</button><select value={poll} onChange={e=>setPoll(e.target.value as Poll)} className="subpanel rounded-lg bg-transparent px-2 py-1.5"><option value="off">OFF</option><option value="10">10 sec</option><option value="30">30 sec</option><option value="60">60 sec</option><option value="300">5 min</option></select><button onClick={()=>setLang(lang==="ar"?"en":"ar")} className="subpanel rounded-lg p-1.5"><Languages size={14}/></button><button onClick={()=>setTheme(theme==="dark"?"light":"dark")} className="subpanel rounded-lg p-1.5">{theme==="dark"?<Sun size={14}/>:<Moon size={14}/>}</button></div></div><div className="mt-2 flex flex-wrap gap-3 text-[9px]">{snap?.health.map(h=><span key={h.name} className={sc(h.state)}>● {h.name} {h.state}{h.latencyMs!=null?" · "+h.latencyMs+" ms":""} {h.detail?"· "+h.detail:""}</span>)}</div></header>

  <S title={t.overview}><div className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-6">{snap?.assets.map(a=><div key={a.symbol} className="panel rounded-xl p-3"><div className="flex items-start justify-between gap-2"><div><b>{a.label}</b>{a.productBadge&&<div className="wait text-[8px] font-bold">{a.productBadge}</div>}</div><Badge a={a.technical.action}/></div><div className="mt-3 flex items-end justify-between"><span className="num text-xl font-black">{fmt(a.quote.price)}</span><span className={"flex items-center text-xs "+(a.technical.direction==="UP"?"good":a.technical.direction==="DOWN"?"bad":"wait")}>{icon(a.technical.direction)}{fmt(a.quote.change1h,true)}</span></div><div className={a.technical.direction==="UP"?"good":a.technical.direction==="DOWN"?"bad":"muted"}><Spark a={a}/></div><div className="mt-1 flex justify-between text-[9px]"><span className="muted">{t.confidence}</span><b className="num">{a.technical.confidence==null?"—":a.technical.confidence+"%"}</b></div><div className="mt-2 grid grid-cols-3 gap-1 text-[9px]"><div>🔴<b className="num block">{fmt(a.technical.support)}</b></div><div>🟡<b className="num block">{fmt(a.technical.pivot)}</b></div><div>🟢<b className="num block">{fmt(a.technical.breakoutTrigger)}</b></div></div><div className="muted mt-2 flex justify-between text-[8px]"><span>{a.quote.source}</span><span className={sc(a.quote.sessionStatus)}>{a.quote.sessionStatus} · {age(a.quote.timestamp)}</span></div></div>)}</div></S>

  {bm&&<S title={t.bmnr}><div className="panel rounded-xl p-3"><div className="grid grid-cols-2 gap-2 md:grid-cols-6">{[["CURRENT",bm.quote.price],["🔴 SUPPORT",bm.technical.support],["🟡 PIVOT",bm.technical.pivot],["🚀 RECLAIM",bm.technical.breakoutTrigger],["⚠️ BREAKDOWN",bm.technical.breakdownTrigger],["🎯 TARGET",bm.technical.nextTarget]].map((x,i)=><div key={i} className="subpanel rounded-lg p-2"><span className="muted text-[9px]">{x[0]}</span><b className="num mt-1 block">{fmt(x[1] as number|null)}</b></div>)}</div><div className="mt-3 grid grid-cols-2 gap-2 text-[10px] md:grid-cols-6"><div>{t.bid}<b className="num block">{fmt(bm.quote.bid)}</b></div><div>{t.ask}<b className="num block">{fmt(bm.quote.ask)}</b></div><div>{t.spread}<b className="num block">{fmt((bm.context as any)?.spreadBps)} bps</b></div><div>1H<b className="num block">{fmt(bm.quote.change1h,true)}</b></div><div>{t.imbalance}<b className="num block">{fmt((bm.context as any)?.orderBookImbalance,true)}</b></div><div>{t.trades}<b className="num block">{fmt((bm.context as any)?.trades)}</b></div></div></div></S>}

  {bmnu&&<S title={t.bmnu}><div className="panel grid grid-cols-2 gap-2 rounded-xl p-3 md:grid-cols-6">{[["CURRENT",bmnu.quote.price],[t.dayLow,bmnu.quote.low],[t.vwap,bmnu.quote.vwap],[t.trigger,bmnu.technical.breakoutTrigger],[t.target,bmnu.technical.nextTarget]].map((x,i)=><div key={i}><span className="muted text-[9px]">{x[0]}</span><b className="num block">{fmt(x[1] as number|null)}</b></div>)}<div><span className="muted text-[9px]">{t.action}</span><Badge a={bmnu.technical.action}/></div></div></S>}

  <S title={t.important}><div className="panel table-wrap rounded-xl"><table className="min-w-[850px] text-[10px]"><thead><tr>{[t.asset,t.price,t.support,t.pivot,t.trigger,t.target,t.invalid,t.action].map((x:string)=><th key={x} className="muted px-3 py-2 text-start">{x}</th>)}</tr></thead><tbody>{snap?.assets.map(a=><tr key={a.symbol}><td className="px-3 py-2 font-black">{a.label}</td><td className="num px-3 py-2">{fmt(a.quote.price)}</td><td className="num bad px-3 py-2 font-bold">{fmt(a.technical.support)}</td><td className="num wait px-3 py-2 font-bold">{fmt(a.technical.pivot)}</td><td className="num good px-3 py-2 font-bold">{fmt(a.technical.breakoutTrigger)}</td><td className="num good px-3 py-2">{fmt(a.technical.nextTarget)}</td><td className="num bad px-3 py-2">{fmt(a.technical.invalidation)}</td><td className="px-3 py-2"><Badge a={a.technical.action}/></td></tr>)}</tbody></table></div></S>

  <S title={t.signals}><div className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-6">{snap?.assets.map(a=><div key={a.symbol} className="panel rounded-lg p-2 text-[10px]"><b>{a.label}</b><div className={"num mt-1 text-sm font-black "+(a.technical.direction==="UP"?"good":a.technical.direction==="DOWN"?"bad":"wait")}>{fmt(a.technical.breakoutTrigger)} = {a.technical.direction==="UP"?"↑":a.technical.direction==="DOWN"?"↓":"→"}</div></div>)}</div></S>
  <S title="Alerts"><div className="grid gap-2 md:grid-cols-3">{alerts.length?alerts.map((x,i)=><div key={i} className="panel rounded-lg p-2 text-[10px] font-bold">{x}</div>):<div className="panel muted rounded-lg p-2 text-[10px]">—</div>}</div></S>

  <S title={t.hourly}><div className="panel table-wrap rounded-xl"><table className="min-w-[1300px] text-[10px]"><thead><tr>{[t.asset,t.price,t.market,t.direction,t.confidence,t.support,t.down,t.resistance,t.up,t.entry,t.tp,t.stop,t.risk,t.news,t.action,t.provider,t.fresh].map((x:string)=><th key={x} className="muted px-3 py-2 text-start">{x}</th>)}</tr></thead><tbody>{snap?.assets.map(a=>{const q=a.quote,x=a.technical;return <tr key={a.symbol}><td className="px-3 py-2 font-black">{a.label}</td><td className="num px-3 py-2">{fmt(q.price)}</td><td className={"px-3 py-2 "+sc(q.sessionStatus)}>{q.sessionStatus}</td><td className="px-3 py-2">{icon(x.direction)}</td><td className="num px-3 py-2">{x.confidence==null?"—":x.confidence+"%"}</td><td className="num bad px-3 py-2">{fmt(x.support)}</td><td className="num px-3 py-2">{fmt(distance(q.price,x.support,"down"),true)}</td><td className="num good px-3 py-2">{fmt(x.resistance)}</td><td className="num px-3 py-2">{fmt(distance(q.price,x.resistance,"up"),true)}</td><td className="num px-3 py-2">{x.entryLow==null?"—":fmt(x.entryLow)+"–"+fmt(x.entryHigh)}</td><td className="num px-3 py-2">{fmt(x.nextTarget)}</td><td className="num px-3 py-2">{fmt(x.invalidation)}</td><td className="px-3 py-2">{x.risk}</td><td className="num px-3 py-2">{a.news?.score==null?"—":a.news.score}</td><td className="px-3 py-2"><Badge a={x.action}/></td><td className="px-3 py-2">{q.source}</td><td className={"px-3 py-2 "+sc(q.sessionStatus)}>{age(q.timestamp)}</td></tr>})}</tbody></table></div><div className="muted mt-1 text-[9px]">{t.distanceNote}</div></S>

  <S title="Chart"><MarketChart assets={snap?.assets||[]}/></S>

  <S title={t.derivatives}><div className="grid gap-2 md:grid-cols-2">{snap?.assets.filter(a=>a.derivatives).map(a=><div key={a.symbol} className="panel rounded-xl p-3"><div className="flex justify-between"><b>{a.label}</b><Badge a={a.technical.action}/></div><div className="mt-2 grid grid-cols-3 gap-2 text-[10px]"><div>{t.price}<b className="num block">{fmt(a.quote.price)}</b></div><div>{t.oi}<b className="num block">{fmt(a.derivatives?.openInterest)}</b></div><div>{t.doi}<b className="num block">{fmt(a.derivatives?.openInterestChange,true)}</b></div><div>{t.taker}<b className="num block">{a.derivatives?.takerRatio==null?"—":a.derivatives.takerRatio.toFixed(3)}</b></div><div>{t.funding}<b className="num block">{a.derivatives?.fundingRate==null?"—":(a.derivatives.fundingRate*100).toFixed(4)+"%"}</b></div><div>{t.volume}<b className="num block">{fmt(a.quote.volume)}</b></div></div></div>)}</div></S>

  <S title={t.semi}><div className="panel rounded-xl p-3"><div className="grid grid-cols-2 gap-2 md:grid-cols-5">{ctx.map(a=><div key={a.symbol} className="subpanel rounded-lg p-2"><div className="flex justify-between text-[10px] font-black"><span>{a.label}</span><span className={(a.quote.change24h||0)>0?"good":(a.quote.change24h||0)<0?"bad":"muted"}>{(a.quote.change24h||0)>0?"↑":(a.quote.change24h||0)<0?"↓":"→"}</span></div><div className="num mt-1 text-sm font-bold">{fmt(a.quote.price)}</div><div className="num muted text-[9px]">{fmt(a.quote.change24h,true)}</div></div>)}</div><div className="mt-3 flex gap-4 text-[10px]"><b>{t.breadth}: {up}/{ctx.length} ↑</b><b className={bias==="STRONG"?"good":bias==="WEAK"?"bad":"wait"}>{t.sectorBias}: {bias}</b></div></div></S>

  {(soxl||soxs)&&<S title={t.pair}><div className="grid gap-2 md:grid-cols-2">{[soxl,soxs].filter(Boolean).map(a=><div key={a!.symbol} className="panel rounded-xl p-3"><div className="flex justify-between"><div><b>{a!.label}</b><div className="muted text-[8px]">{a!.productBadge}</div></div><Badge a={a!.technical.action}/></div><div className="mt-2 grid grid-cols-3 gap-2 text-[10px]"><div>{t.current}<b className="num block">{fmt(a!.quote.price)}</b></div><div>{t.vwap}<b className="num block">{fmt(a!.quote.vwap)}</b></div><div>{t.support}<b className="num bad block">{fmt(a!.technical.support)}</b></div><div>{t.trigger}<b className="num good block">{fmt(a!.technical.breakoutTrigger)}</b></div><div>{t.target}<b className="num good block">{fmt(a!.technical.nextTarget)}</b></div><div>{t.risk}<b className="block">{a!.technical.risk}</b></div></div></div>)}</div></S>}

  <S title={t.changes}><div className="panel table-wrap rounded-xl"><table className="min-w-[820px] text-[10px]"><thead><tr>{[t.asset,t.previous,t.current,t.delta,t.prevAction,t.curAction,t.keyChange].map((x:string)=><th key={x} className="muted px-3 py-2 text-start">{x}</th>)}</tr></thead><tbody>{snap?.assets.map(a=>{const p=prev.get(a.symbol),d=p?.price&&a.quote.price?100*(a.quote.price-p.price)/p.price:null,key=p?(p.action!==a.technical.action?p.action+" → "+a.technical.action:Math.abs(d||0)>=1?"PRICE MOVE":"—"):t.noHistory;return <tr key={a.symbol}><td className="px-3 py-2 font-black">{a.label}</td><td className="num px-3 py-2">{fmt(p?.price)}</td><td className="num px-3 py-2">{fmt(a.quote.price)}</td><td className="num px-3 py-2">{fmt(d,true)}</td><td className="px-3 py-2">{p?.action||"—"}</td><td className="px-3 py-2">{a.technical.action}</td><td className="px-3 py-2">{key}</td></tr>})}</tbody></table></div></S>

  <S title={t.indicators}><div className="panel table-wrap rounded-xl"><table className="min-w-[1100px] text-[10px]"><thead><tr>{[t.asset,"1H %","24H %",t.oi,t.taker,t.funding,t.volume,t.high,t.low,t.vwap,t.bid,t.ask,t.provider].map((x:string)=><th key={x} className="muted px-3 py-2 text-start">{x}</th>)}</tr></thead><tbody>{snap?.assets.map(a=><tr key={a.symbol}><td className="px-3 py-2 font-black">{a.label}</td><td className="num px-3 py-2">{fmt(a.quote.change1h,true)}</td><td className="num px-3 py-2">{fmt(a.quote.change24h,true)}</td><td className="num px-3 py-2">{fmt(a.derivatives?.openInterest)}</td><td className="num px-3 py-2">{a.derivatives?.takerRatio==null?"—":a.derivatives.takerRatio.toFixed(3)}</td><td className="num px-3 py-2">{a.derivatives?.fundingRate==null?"—":(a.derivatives.fundingRate*100).toFixed(4)+"%"}</td><td className="num px-3 py-2">{fmt(a.quote.volume)}</td><td className="num px-3 py-2">{fmt(a.quote.high)}</td><td className="num px-3 py-2">{fmt(a.quote.low)}</td><td className="num px-3 py-2">{fmt(a.quote.vwap)}</td><td className="num px-3 py-2">{fmt(a.quote.bid)}</td><td className="num px-3 py-2">{fmt(a.quote.ask)}</td><td className="px-3 py-2">{a.quote.source}</td></tr>)}</tbody></table></div></S>
  <footer className="muted py-5 text-center text-[9px]">{t.footer}</footer>
 </main>
}