const {num,atr,swingLevels}=require('./pretrade');
function distance(price,target,side){price=num(price);target=num(target);if(price==null||target==null||price<=0)return null;return side==='down'?100*(price-target)/price:100*(target-price)/price}
function equitySignal(x){if(!x?.available)return{actionLabel:'WAIT',confidence:null,reason:'data unavailable',entryZone:null,invalidation:null,target:null,evidenceScore:null};
 const p=num(x.price),v=num(x.vwap),rv=num(x.relativeVolume),bid=num(x.bid),ask=num(x.ask),sup=num(x.support),res=num(x.resistance),a=num(x.atr);if(p==null)return{actionLabel:'WAIT',confidence:null,reason:'price unavailable'};
 let score=50,used=0;if(v!=null){score+=p>v?12:-12;used++}if(sup!=null&&res!=null){const mid=(sup+res)/2;score+=p>mid?8:-8;used++}if(rv!=null){if(rv>=1.2)score+=p>v?8:-8;used++}if(bid!=null&&ask!=null&&ask>0){const spread=10000*(ask-bid)/((ask+bid)/2);if(spread>35)return{actionLabel:'WAIT',confidence:'LOW',reason:'wide bid/ask spread',evidenceScore:score};used++}if(used<2)return{actionLabel:'WAIT',confidence:'LOW',reason:'insufficient verified evidence',evidenceScore:score};
 const actionLabel=score>=68?'BUY BIAS':score<=32?'SELL/AVOID BIAS':'WAIT',confidence=used>=4&&Math.abs(score-50)>=22?'MODERATE':'LOW';let entryZone=null,invalidation=null,target=null;
 if(actionLabel==='BUY BIAS'&&a&&sup!=null&&res!=null){entryZone:[Math.max(sup,p-.3*a),p+.08*a];entryZone=[Math.max(sup,p-.3*a),p+.08*a];invalidation=Math.min(sup-.15*a,p-a);target=Math.max(res,p+1.4*a)}
 if(actionLabel==='SELL/AVOID BIAS'&&a&&sup!=null&&res!=null){entryZone=[p-.08*a,Math.min(res,p+.3*a)];invalidation=Math.max(res+.15*a,p+a);target=Math.min(sup,p-1.4*a)}
 return{actionLabel,confidence,reason:actionLabel==='WAIT'?'signals conflict or lack confirmation':'price structure/VWAP evidence aligned',entryZone,invalidation,target,evidenceScore:Math.max(0,Math.min(100,score))}
}
function strengthScore(x){if(!x?.available)return null;let s=50;if(x.actionLabel==='BUY BIAS')s+=18;if(x.actionLabel==='SELL/AVOID BIAS')s-=18;const up=num(x.upsidePct),down=num(x.downsidePct);if(up!=null&&down!=null)s+=Math.max(-12,Math.min(12,(up-down)*2));if(x.confidence==='HIGH')s+=8;else if(x.confidence==='MODERATE')s+=4;return Math.max(0,Math.min(100,s))}
module.exports={distance,equitySignal,strengthScore};