const {num}=require('./pretrade');
function configured(){return !!((process.env.US_MARKET_DATA_URL&&process.env.US_MARKET_DATA_KEY)||(process.env.ALPACA_API_KEY_ID&&process.env.ALPACA_API_SECRET_KEY))}
async function json(url,opts={},timeout=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...opts,signal:c.signal,cache:'no-store'}),j=await r.json().catch(()=>null);if(!r.ok||!j)throw new Error('upstream '+r.status);return j}finally{clearTimeout(t)}}
function alpacaHeaders(){return {'APCA-API-KEY-ID':process.env.ALPACA_API_KEY_ID,'APCA-API-SECRET-KEY':process.env.ALPACA_API_SECRET_KEY,Accept:'application/json'}}
function barRow(b){if(!b)return null;return [Date.parse(b.t||new Date().toISOString()),b.o,b.h,b.l,b.c,b.v]}
async function alpaca(symbol){if(!process.env.ALPACA_API_KEY_ID||!process.env.ALPACA_API_SECRET_KEY)return null;const base=(process.env.ALPACA_DATA_BASE_URL||'https://data.alpaca.markets').replace(/\/$/,'');const h=alpacaHeaders(),snap=await json(base+'/v2/stocks/'+encodeURIComponent(symbol)+'/snapshot?feed=iex',{headers:h});let bars=[];try{const end=new Date().toISOString(),start=new Date(Date.now()-2*86400000).toISOString(),b=await json(base+'/v2/stocks/'+encodeURIComponent(symbol)+'/bars?timeframe=5Min&start='+encodeURIComponent(start)+'&end='+encodeURIComponent(end)+'&limit=500&feed=iex&adjustment=raw',{headers:h});bars=(b.bars||[]).map(barRow).filter(Boolean)}catch{}
 const lt=snap.latestTrade||{},lq=snap.latestQuote||{},mb=snap.minuteBar||{},db=snap.dailyBar||{},pb=snap.prevDailyBar||{},price=num(lt.p??mb.c??db.c),bid=num(lq.bp),ask=num(lq.ap),observedAt=lt.t||lq.t||mb.t||db.t||null;
 return{price,open:num(db.o),high:num(db.h),low:num(db.l),previousClose:num(pb.c),volume:num(db.v),relativeVolume:null,bid,ask,vwap:num(db.vw),bars,source:'alpaca-iex',observedAt,priceStatus:null}
}
async function generic(symbol){const base=process.env.US_MARKET_DATA_URL,key=process.env.US_MARKET_DATA_KEY;if(!base||!key)return null;return json(base.replace(/\/$/,'')+'/snapshot?symbol='+encodeURIComponent(symbol),{headers:{Authorization:'Bearer '+key,Accept:'application/json'}})}
async function getSnapshot(symbol){return await alpaca(symbol)||await generic(symbol)}
module.exports={configured,getSnapshot};