-- Trader Command Center v75.2 hourly history
create table if not exists public.tcc_hourly_reports (
 id bigint generated by default as identity primary key,
 symbol text not null,
 price double precision not null,
 action_label text not null check (action_label in ('BUY BIAS','SELL/AVOID BIAS','WAIT')),
 price_status text,
 observed_at timestamptz not null default now(),
 hour_bucket timestamptz not null
);
create unique index if not exists tcc_hourly_reports_symbol_hour_uidx on public.tcc_hourly_reports(symbol,hour_bucket);
create index if not exists tcc_hourly_reports_symbol_time_idx on public.tcc_hourly_reports(symbol,observed_at desc);
alter table public.tcc_hourly_reports enable row level security;
revoke all on public.tcc_hourly_reports from anon, authenticated;
grant all on public.tcc_hourly_reports to service_role;
