const H={'Content-Type':'application/json','X-Content-Type-Options':'nosniff'};
const U=()=>process.env.SUPABASE_URL,K=()=>process.env.SUPABASE_SERVICE_ROLE_KEY;
async function db(path){if(!U()||!K())return{configured:false};const r=await fetch(`${U()}/rest/v1/${path}`,{headers:{...H,apikey:K(),Authorization:`Bearer ${K()}`}}),text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(`DB ${r.status}`);return{configured:true,data}}
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null},mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
function se(a){if(a.length<2)return null;const m=mean(a),sd=Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1));return sd/Math.sqrt(a.length)}
function stat(rows,h,filter=()=>true){const vals=rows.filter(filter).map(r=>n(r[`outcome_${h}`])).filter(v=>v!=null);const m=mean(vals),err=se(vals);return{samples:vals.length,avgReturn:m,positiveRate:vals.length?100*vals.filter(v=>v>0).length/vals.length:null,ci95:err==null?null:1.96*err}}
function parseNum(v){const m=String(v??'').replace(/,/g,'').match(/[-+]?\d+(?:\.\d+)?/);return m?n(m[0]):null}
function factors(r){const o=r.orderflow||{},d=r.derivatives||{},mtf=r.mtf||{};return{evidence:n(r.evidence_score),quality:n(r.quality_score),state:String(r.state||''),regime:String(r.regime||''),mtf:String(mtf.alignment||''),depth:parseNum(o.depth),taker:parseNum(o.taker),spread:parseNum(o.spread),oi5:parseNum(d.oi5),oi15:parseNum(d.oi15),funding:parseNum(d.funding),deviation:parseNum(d.deviation)}}
function split(rows,key){const a=[],b=[];for(const r of rows){const v=factors(r)[key];if(v==null)continue;(v>=0?a:b).push(r)}return[a,b]}
module.exports=async function handler(req,res){Object.entries(H).forEach(([k,v])=>res.setHeader(k,v));res.setHeader('Cache-Control','no-store');if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({error:'Method not allowed'})}const symbol=String(req.query?.symbol||'BTCUSDT').toUpperCase();if(!/^[A-Z0-9]{3,24}$/.test(symbol))return res.status(400).json({error:'invalid symbol'});try{const got=await db(`tcc_observations?symbol=eq.${encodeURIComponent(symbol)}&select=state,evidence_score,quality_score,regime,mtf,derivatives,orderflow,anomaly,outcome_15m,outcome_1h,outcome_4h,observed_at&order=observed_at.asc&limit=2000`);if(!got.configured)return res.status(200).json({configured:false,modelVersion:'v68.1',note:'Persistent database not configured'});const rows=Array.isArray(got.data)?got.data:[],horizons=['15m','1h','4h'],MIN=30,TRAIN_MIN=60;const overall={},regimes={},factorStats={};for(const h of horizons){overall[h]=stat(rows,h);regimes[h]={trendingUp:stat(rows,h,r=>/TRENDING UP/i.test(r.regime||'')),trendingDown:stat(rows,h,r=>/TRENDING DOWN/i.test(r.regime||'')),range:stat(rows,h,r=>/RANGE/i.test(r.regime||''))};factorStats[h]={};for(const key of ['depth','taker','oi5','oi15']){const [pos,neg]=split(rows,key);factorStats[h][key]={positive:stat(pos,h),negative:stat(neg,h)}}factorStats[h].highQuality=stat(rows,h,r=>(n(r.quality_score)||0)>=85);factorStats[h].lowQuality=stat(rows,h,r=>(n(r.quality_score)||0)<65);factorStats[h].highEvidence=stat(rows,h,r=>Math.abs((n(r.evidence_score)||50)-50)>=15);factorStats[h].neutralEvidence=stat(rows,h,r=>Math.abs((n(r.evidence_score)||50)-50)<10)}const cut=Math.floor(rows.length*.7),train=rows.slice(0,cut),test=rows.slice(cut),walkForward={ready:train.length>=TRAIN_MIN&&test.length>=MIN,trainSamples:train.length,testSamples:test.length,train:{},test:{}};for(const h of horizons){walkForward.train[h]=stat(train,h);walkForward.test[h]=stat(test,h)}let readiness='INSUFFICIENT HISTORY';const evaluated=Math.max(...horizons.map(h=>overall[h].samples));if(evaluated>=100)readiness='CALIBRATION READY';else if(evaluated>=MIN)readiness='EARLY CALIBRATION';return res.status(200).json({configured:true,modelVersion:'v68.1',symbol,totalRows:rows.length,evaluatedSamples:evaluated,minSamples:MIN,readiness,overall,regimes,factors:factorStats,walkForward,guardrail:'Statistics are descriptive calibration evidence, not a probability forecast. Deterministic scoring remains primary unless minimum-sample and walk-forward checks are satisfied.'})}catch(e){return res.status(500).json({error:'calibration read failed'})}};
