const H={'Content-Type':'application/json','X-Content-Type-Options':'nosniff'};
const U=()=>process.env.SUPABASE_URL,K=()=>process.env.SUPABASE_SERVICE_ROLE_KEY;const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
async function db(path,opts={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),5500);try{const r=await fetch(`${U()}/rest/v1/${path}`,{...opts,signal:c.signal,headers:{...H,apikey:K(),Authorization:`Bearer ${K()}`,Prefer:opts.prefer||'return=representation',...(opts.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(`DB ${r.status}`);return data}finally{clearTimeout(t)}}
function base(){return process.env.VERCEL_PROJECT_PRODUCTION_URL?`https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`:(process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:null)}
async function market(path){const c=new AbortController(),t=setTimeout(()=>c.abort(),5500);try{const r=await fetch(`${base()}/api/market?market=futures&path=${encodeURIComponent(path)}`,{signal:c.signal,cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||`market ${r.status}`);return j}finally{clearTimeout(t)}}
async function authorized(req){const provided=String(req.headers?.['x-tcc-observer-token']||'');if(!provided)return false;const rows=await db('tcc_runtime_secrets?key=eq.observer_token&select=value&limit=1');return String(rows?.[0]?.value||'').length>=32&&provided===String(rows[0].value)}
function validProv(p){const ticker=String(p?.ticker||''),candles=Array.isArray(p?.candles)?p.candles:[];return (p?.dataClass==='futures-validated'||ticker.startsWith('binance-futures'))&&candles.length===4&&candles.every(x=>String(x||'').startsWith('binance-futures'))}
async function exactPrice(symbol,targetMs){const start=targetMs-60000,end=targetMs+120000,j=await market(`/fapi/v1/klines?symbol=${symbol}&interval=1m&startTime=${start}&endTime=${end}&limit=4`);if(!(j.market==='futures'&&j.capabilities?.derivatives===true&&!String(j.source||'').includes('spot')))return null;const rows=Array.isArray(j.data)?j.data:[];if(!rows.length)return null;rows.sort((a,b)=>Math.abs(Number(a[0])-targetMs)-Math.abs(Number(b[0])-targetMs));return{price:n(rows[0][4]),openTime:Number(rows[0][0]),source:j.source||null,degraded:!!j.degraded}}
async function run(symbol){const horizons=[['15m',9e5],['1h',36e5],['4h',144e5]],summary={symbol,evaluated:{},skippedInvalidProvenance:{}};for(const[h,ms]of horizons){const col=`evaluated_${h}`,out=`outcome_${h}`,before=new Date(Date.now()-ms).toISOString(),due=await db(`tcc_observations?symbol=eq.${symbol}&${col}=eq.false&observed_at=lte.${encodeURIComponent(before)}&select=id,price,observed_at,provenance&order=observed_at.asc&limit=100`);let done=0,skipped=0;for(const row of due||[]){if(!validProv(row.provenance)){skipped++;continue}const p=n(row.price);if(!p)continue;try{const target=new Date(row.observed_at).getTime()+ms,f=await exactPrice(symbol,target);if(f?.price==null)continue;await db(`tcc_observations?id=eq.${row.id}`,{method:'PATCH',body:JSON.stringify({[out]:100*(f.price-p)/p,[col]:true})});done++}catch{}}
summary.evaluated[h]=done;summary.skippedInvalidProvenance[h]=skipped}return summary}
module.exports=async function(req,res){Object.entries(H).forEach(([k,v])=>res.setHeader(k,v));res.setHeader('Cache-Control','no-store');if(!['GET','POST'].includes(req.method))return res.status(405).json({error:'Method not allowed'});if(!U()||!K())return res.status(200).json({configured:false});if(!(await authorized(req)))return res.status(401).json({error:'evaluator authorization required'});const requested=String(req.query?.symbol||'ALL').toUpperCase(),supported=['BTCUSDT','ETHUSDT'],symbols=requested==='ALL'?supported:supported.includes(requested)?[requested]:[];if(!symbols.length)return res.status(400).json({error:'unsupported symbol',supported});const results=[];for(const s of symbols)results.push(await run(s));return res.status(200).json({configured:true,evaluator:'exchange-futures-1m-nearest-v72.1',results})};