const {listInstruments}=require('../lib/instruments');const {num}=require('../lib/pretrade');const {distance,equitySignal,strengthScore}=require('../lib/hourly');
function base(){return process.env.VERCEL_URL?'https://'+process.env.VERCEL_URL:(process.env.VERCEL_PROJECT_PRODUCTION_URL?'https://'+process.env.VERCEL_PROJECT_PRODUCTION_URL:null)}
async function j(p){const b=base();if(!b)return{available:false,error:'deployment host unavailable'};const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(b+p,{signal:c.signal,cache:'no-store'}),x=await r.json().catch(()=>({}));return r.ok?x:{available:false,error:x.error||'unavailable'}}catch(e){return{available:false,error:e.message}}finally{clearTimeout(t)}}
const action=d=>d==='LONG BIAS'?'BUY BIAS':d==='SHORT BIAS'?'SELL/AVOID BIAS':'WAIT';
const hourBucket=iso=>new Date(Math.floor(new Date(iso).getTime()/3600000)*3600000).toISOString();
async function previous(symbol,before){const U=process.env.SUPABASE_URL,K=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!U||!K)return null;try{const bucket=hourBucket(before),q='tcc_hourly_reports?symbol=eq.'+encodeURIComponent(symbol)+'&hour_bucket=lt.'+encodeURIComponent(bucket)+'&select=symbol,price,action_label,observed_at,hour_bucket&order=hour_bucket.desc&limit=1',r=await fetch(U+'/rest/v1/'+q,{headers:{apikey:K,Authorization:'Bearer '+K},cache:'no-store'}),x=await r.json();return r.ok&&Array.isArray(x)?x[0]||null:null}catch{return null}}
async function store(rows,observed){const U=process.env.SUPABASE_URL,K=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!U||!K)return false;try{const hour=hourBucket(observed),payload=rows.filter(x=>x.available&&num(x.price)!=null).map(x=>({symbol:x.symbol,price:x.price,action_label:x.actionLabel,observed_at:observed,hour_bucket:hour,price_status:x.priceStatus}));if(!payload.length)return false;const r=await fetch(U+'/rest/v1/tcc_hourly_reports?on_conflict=symbol,hour_bucket',{method:'POST',headers:{'Content-Type':'application/json',apikey:K,Authorization:'Bearer '+K,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});return r.ok}catch{return false}}
function applySectorGuard(assets,ctx){const soxl=assets.find(x=>x.symbol==='SOXL'),soxs=assets.find(x=>x.symbol==='SOXS');if(!ctx?.available||!soxl||!soxs)return;soxl.sectorConfirmation=ctx.state;soxs.sectorConfirmation=ctx.state==='BULLISH'?'BEARISH':ctx.state==='BEARISH'?'BULLISH':ctx.state;
 if(soxl.actionLabel==='BUY BIAS'&&ctx.state==='BEARISH'){soxl.actionLabel='WAIT';soxl.decisionReason='sector confirmation conflicts with SOXL';}
 if(soxs.actionLabel==='BUY BIAS'&&ctx.state==='BULLISH'){soxs.actionLabel='WAIT';soxs.decisionReason='sector confirmation conflicts with SOXS';}
 if(soxl.actionLabel==='BUY BIAS'&&soxs.actionLabel==='BUY BIAS'){if((soxl.evidenceScore??50)>=(soxs.evidenceScore??50)){soxs.actionLabel='WAIT';soxs.decisionReason='inverse-product consistency guard';}else{soxl.actionLabel='WAIT';soxl.decisionReason='inverse-product consistency guard';}}
}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json');if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const observed=new Date().toISOString(),persist=String(req.query?.persist||'0')==='1';
 const [ctx,news]=await Promise.all([j('/api/us-context'),j('/api/news-sentiment')]);
 let assets=await Promise.all(listInstruments().map(async i=>{if(i.marketClass==='equity'){const x=await j('/api/us-snapshot?symbol='+i.symbol),sig=equitySignal(x),p=num(x.price),down=num(x.support),up=num(x.resistance);return{symbol:i.label,market:i.marketClass,price:p,priceStatus:x.priceStatus||'غير متاح',session:x.session||null,confidence:sig.confidence,downsideTarget:down,downsidePct:distance(p,down,'down'),upsideTarget:up,upsidePct:distance(p,up,'up'),pivot:num(x.pivot),entryZone:sig.entryZone||null,invalidation:sig.invalidation||null,target:sig.target||up,newsSentiment:news?.items?.[i.label]?.score??null,actionLabel:sig.actionLabel,decisionReason:sig.reason,available:!!x.available,leveraged:x.leveraged||null,source:x.source||null,evidenceScore:sig.evidenceScore??null,relativeVolume:num(x.relativeVolume),vwap:num(x.vwap),bid:num(x.bid),ask:num(x.ask)}}const x=await j('/api/pretrade?symbol='+i.symbol+'&requestId=hourly'),p=num(x.referencePrice),down=num(x.support),up=num(x.resistance),spot=i.marketClass==='spot'?await j('/api/spot-snapshot?symbol='+i.symbol):null;return{symbol:i.label,market:i.marketClass,price:p,priceStatus:x.freshness?.fresh?'LIVE':(x.freshness?'Delayed':'غير متاح'),session:'24/7',confidence:x.confidenceClass||null,downsideTarget:down,downsidePct:distance(p,down,'down'),upsideTarget:up,upsidePct:distance(p,up,'up'),entryZone:x.entryZone??null,invalidation:num(x.invalidation),target:num(x.targets?.[0]),pivot:num(x.entryZone?.[0]),newsSentiment:news?.items?.[i.label]?.score??null,actionLabel:action(x.decision),decisionReason:x.decisionReason||null,available:x.decision!=='DATA UNAVAILABLE'&&p!=null,source:x.provenance||null,evidenceScore:num(x.evidenceScore),derivatives:i.marketClass==='futures'?{consensus:x.consensus||null}:null,bmnr:spot?{hourlyHigh:num(spot.hourlyHigh),hourlyLow:num(spot.hourlyLow),volume24h:num(spot.volume24h),turnover24h:num(spot.quoteVolume24h),tradeCount:num(spot.tradeCount),bid:num(spot.bid),ask:num(spot.ask),spreadBps:num(spot.spreadBps),orderBookImbalance:num(spot.orderBook?.imbalance)}:null}}));
 applySectorGuard(assets,ctx);
 const changes=await Promise.all(assets.map(async x=>{const prev=await previous(x.symbol,observed);if(!prev||num(prev.price)==null||num(x.price)==null)return{symbol:x.symbol,available:false};return{symbol:x.symbol,available:true,previousAction:prev.action_label,currentAction:x.actionLabel,priceChangePct:100*(x.price-prev.price)/prev.price,previousObservedAt:prev.observed_at}}));
 const ranked=assets.map(x=>({...x,strengthScore:strengthScore(x)})).filter(x=>x.strengthScore!=null).sort((a,b)=>b.strengthScore-a.strengthScore).map((x,n)=>({rank:n+1,symbol:x.symbol,score:x.strengthScore,actionLabel:x.actionLabel}));
 if(persist)await store(assets,observed);
 return res.status(200).json({version:'v76',observedAt:observed,persisted:persist,reportTimeSaudi:new Intl.DateTimeFormat('ar-SA',{timeZone:'Asia/Riyadh',dateStyle:'medium',timeStyle:'medium'}).format(new Date()),assets,changesSincePrevious:changes,strengthRanking:ranked,sectorConfirmation:ctx?.available?ctx:null,newsStatus:news?.available?'VERIFIED':'غير متاح — no verified news provider connected',note:'Percentages are price distances to technical zones, not probabilities. WAIT is used when evidence conflicts or is incomplete.'})};