const H={'Content-Type':'application/json','X-Content-Type-Options':'nosniff'};
const U=()=>process.env.SUPABASE_URL,K=()=>process.env.SUPABASE_SERVICE_ROLE_KEY;
const SYMBOLS=['BTCUSDT','ETHUSDT','BMNRBUSDT','USTCUSDT'];
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
async function db(path,opts={}){if(!U()||!K())return{configured:false};const r=await fetch(`${U()}/rest/v1/${path}`,{...opts,headers:{...H,apikey:K(),Authorization:`Bearer ${K()}`,Prefer:opts.prefer||'return=representation',...(opts.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(`DB ${r.status}`);return{configured:true,data}}
async function market(path){const c=new AbortController(),t=setTimeout(()=>c.abort(),5500);try{const base=process.env.VERCEL_PROJECT_PRODUCTION_URL?`https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`:(process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:null);if(!base)throw new Error('no host');const r=await fetch(`${base}/api/market?market=futures&path=${encodeURIComponent(path)}`,{signal:c.signal,headers:{Accept:'application/json'}}),j=await r.json();if(!r.ok)throw new Error(j.error||`market ${r.status}`);return j}finally{clearTimeout(t)}}
function ema(v,p){if(!v.length)return NaN;const k=2/(p+1);let e=v[0];for(let i=1;i<v.length;i++)e=v[i]*k+e*(1-k);return e}
function rsi(rows,p=14){if(!rows?.length||rows.length<p+1)return NaN;const c=rows.map(x=>+x[4]);let g=0,l=0;for(let i=c.length-p;i<c.length;i++){const d=c[i]-c[i-1];if(d>0)g+=d;else l-=d}return l?100-100/(1+(g/p)/(l/p)):100}
function dir(rows){if(!rows?.length||rows.length<55)return{state:'MIXED',score:50};const c=rows.map(x=>+x[4]),px=c.at(-1),e20=ema(c.slice(-90),20),e50=ema(c.slice(-150),50),rv=rsi(rows),ret=c.at(-4)?100*(px-c.at(-4))/c.at(-4):0;let s=50+(px>e20?16:-16)+(e20>e50?16:-16)+(rv>55?10:rv<45?-10:0)+(ret>0?8:-8);s=Math.max(0,Math.min(100,s));return{state:s>=60?'UP':s<=40?'DOWN':'MIXED',score:s,rsi:rv}}
async function evaluate(symbol,price){for(const[h,ms]of[['15m',9e5],['1h',36e5],['4h',144e5]]){const before=new Date(Date.now()-ms).toISOString(),col=`evaluated_${h}`,out=`outcome_${h}`,got=await db(`tcc_observations?symbol=eq.${symbol}&${col}=eq.false&observed_at=lte.${encodeURIComponent(before)}&select=id,price&limit=200`);for(const row of(got.data||[])){const p=n(row.price);if(!p)continue;await db(`tcc_observations?id=eq.${row.id}`,{method:'PATCH',body:JSON.stringify({[out]:100*(price-p)/p,[col]:true})})}}}
async function observe(symbol){const [tk,k5,k15,k1,k4,oi,fr]=await Promise.all([market(`/fapi/v1/ticker/24hr?symbol=${symbol}`),market(`/fapi/v1/klines?symbol=${symbol}&interval=5m&limit=180`),market(`/fapi/v1/klines?symbol=${symbol}&interval=15m&limit=180`),market(`/fapi/v1/klines?symbol=${symbol}&interval=1h&limit=180`),market(`/fapi/v1/klines?symbol=${symbol}&interval=4h&limit=180`),market(`/fapi/v1/openInterest?symbol=${symbol}`).catch(()=>null),market(`/fapi/v1/premiumIndex?symbol=${symbol}`).catch(()=>null)]);const price=n(tk.data?.lastPrice??tk.data?.price);if(!price)throw new Error('no price');const states=[k5,k15,k1,k4].map(x=>dir(Array.isArray(x.data)?x.data:[])),up=states.filter(x=>x.state==='UP').length,down=states.filter(x=>x.state==='DOWN').length,raw=states.reduce((s,x)=>s+x.score,0)/states.length,state=raw>=60?'BULLISH':raw<=40?'BEARISH':'MIXED',quality=[tk,k5,k15,k1,k4].filter(Boolean).reduce((s,x)=>s+(x.degraded?70:100),0)/5,bucket=new Date(Math.floor(Date.now()/60000)*60000).toISOString();const existing=await db(`tcc_observations?symbol=eq.${symbol}&observed_at=eq.${encodeURIComponent(bucket)}&select=id&limit=1`);if(existing.data?.length)return{symbol,stored:false,deduped:true};const payload={symbol,observed_at:bucket,price,state,evidence_score:raw,quality_score:quality,regime:up>=3?'TRENDING UP':down>=3?'TRENDING DOWN':'RANGE / MIXED',mtf:{m5:states[0],m15:states[1],h1:states[2],h4:states[3],alignment:`${Math.max(up,down)}/4`},derivatives:{openInterest:n(oi?.data?.openInterest),funding:n(fr?.data?.lastFundingRate),source:fr?.source||oi?.source||null},provenance:{collector:'server-v70',ticker:tk.source,candles:[k5.source,k15.source,k1.source,k4.source]}};await db('tcc_observations',{method:'POST',body:JSON.stringify(payload)});await evaluate(symbol,price);return{symbol,stored:true,state,evidence:raw,quality}}
module.exports=async function(req,res){Object.entries(H).forEach(([k,v])=>res.setHeader(k,v));res.setHeader('Cache-Control','no-store');if(!['GET','POST'].includes(req.method))return res.status(405).json({error:'Method not allowed'});if(!U()||!K())return res.status(200).json({configured:false});const requested=String(req.query?.symbol||'ALL').toUpperCase(),symbols=requested==='ALL'?SYMBOLS:SYMBOLS.includes(requested)?[requested]:[];if(!symbols.length)return res.status(400).json({error:'unsupported symbol'});try{const results=[];for(const s of symbols){try{results.push(await observe(s))}catch(e){results.push({symbol:s,error:e.message})}}return res.status(200).json({configured:true,collector:'server-v70',results})}catch(e){return res.status(500).json({error:'observation failed'})}};