const H={'Content-Type':'application/json','X-Content-Type-Options':'nosniff'};
const U=()=>process.env.SUPABASE_URL,K=()=>process.env.SUPABASE_SERVICE_ROLE_KEY;
const SYMBOLS=['BTCUSDT','ETHUSDT'];
const {num:n,clamp,structure,isFuturesResponse,validFuturesProvenance}=require('../lib/engine');
async function db(path,opts={}){if(!U()||!K())return{configured:false};const c=new AbortController(),t=setTimeout(()=>c.abort(),5500);try{const r=await fetch(`${U()}/rest/v1/${path}`,{...opts,signal:c.signal,headers:{...H,apikey:K(),Authorization:`Bearer ${K()}`,Prefer:opts.prefer||'return=representation',...(opts.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(`DB ${r.status}`);return{configured:true,data,status:r.status}}finally{clearTimeout(t)}}
function base(){return process.env.VERCEL_PROJECT_PRODUCTION_URL?`https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`:(process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:null)}
async function localJson(path,timeout=5500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout),st=Date.now();try{const r=await fetch(base()+path,{signal:c.signal,headers:{Accept:'application/json'},cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return{...j,latency:Date.now()-st}}finally{clearTimeout(t)}}
const market=path=>localJson(`/api/market?market=futures&path=${encodeURIComponent(path)}`);
function depth(book){const clean=a=>(Array.isArray(a)?a:[]).slice(0,20).map(x=>[n(x[0]),n(x[1])]).filter(x=>x[0]!=null&&x[1]!=null),b=clean(book?.bids),a=clean(book?.asks),bn=b.reduce((s,[p,q])=>s+p*q,0),an=a.reduce((s,[p,q])=>s+p*q,0),tot=bn+an;return{imbalance:tot?100*(bn-an)/tot:null,bidNotional:bn,askNotional:an}}
function taker(rows,count=12){let buy=0,total=0;for(const k of(rows||[]).slice(-count)){const q=n(k[7]),tb=n(k[10]);if(q!=null&&tb!=null){total+=q;buy+=tb}}return total?100*(buy-(total-buy))/total:null}
async function authorized(req){const provided=String(req.headers?.['x-tcc-observer-token']||'');if(!provided)return false;const got=await db('tcc_runtime_secrets?key=eq.observer_token&select=value&limit=1');const expected=String(got.data?.[0]?.value||'');return expected.length>=32&&provided===expected}
function nearestHistory(rows,minutes,selector){if(!rows.length)return null;const target=Date.now()-minutes*60000;let best=null,d=Infinity;for(const r of rows){const dd=Math.abs(new Date(r.observed_at).getTime()-target);if(dd<d){d=dd;best=r}}return selector(best)}
async function observe(symbol){const [tk,k5,k15,k1,k4,oi,fr,book,bt,consensus]=await Promise.all([market(`/fapi/v1/ticker/24hr?symbol=${symbol}`),market(`/fapi/v1/klines?symbol=${symbol}&interval=5m&limit=180`),market(`/fapi/v1/klines?symbol=${symbol}&interval=15m&limit=180`),market(`/fapi/v1/klines?symbol=${symbol}&interval=1h&limit=180`),market(`/fapi/v1/klines?symbol=${symbol}&interval=4h&limit=180`),market(`/fapi/v1/openInterest?symbol=${symbol}`).catch(()=>null),market(`/fapi/v1/premiumIndex?symbol=${symbol}`).catch(()=>null),market(`/fapi/v1/depth?symbol=${symbol}&limit=20`).catch(()=>null),market(`/fapi/v1/ticker/bookTicker?symbol=${symbol}`).catch(()=>null),localJson(`/api/consensus?symbol=${symbol}`).catch(()=>null)]);
const core=[tk,k5,k15,k1,k4];if(!core.every(isFuturesResponse))throw new Error('futures-core-unavailable');const price=n(tk.data?.lastPrice??tk.data?.price);if(!price)throw new Error('no price');const engine=structure({m5:k5.data,m15:k15.data,h1:k1.data,h4:k4.data}),bucket=new Date(Math.floor(Date.now()/300000)*300000).toISOString();
const oiNow=isFuturesResponse(oi)?n(oi.data?.openInterest):null,fund=isFuturesResponse(fr)?n(fr.data?.lastFundingRate):null,mark=isFuturesResponse(fr)?n(fr.data?.markPrice):null,d=isFuturesResponse(book)?depth(book.data||{}):{imbalance:null,bidNotional:null,askNotional:null},flow=taker(k5.data),bid=isFuturesResponse(bt)?n(bt.data?.bidPrice):null,ask=isFuturesResponse(bt)?n(bt.data?.askPrice):null,mid=bid!=null&&ask!=null?(bid+ask)/2:null,spread=mid?10000*(ask-bid)/mid:null,deviation=mark&&price?10000*(mark-price)/price:null;
const hist=await db(`tcc_observations?symbol=eq.${symbol}&observed_at=lt.${encodeURIComponent(bucket)}&select=price,derivatives,observed_at,provenance&order=observed_at.desc&limit=24`),rows=(hist.data||[]).filter(x=>validFuturesProvenance(x.provenance)),pct=(a,b)=>a!=null&&b?100*(a-b)/b:null,oi5=pct(oiNow,nearestHistory(rows,5,r=>n(r?.derivatives?.openInterest))),oi15=pct(oiNow,nearestHistory(rows,15,r=>n(r?.derivatives?.openInterest))),oi1h=pct(oiNow,nearestHistory(rows,60,r=>n(r?.derivatives?.openInterest))),prev=rows[0],price5=pct(price,n(prev?.price));
const coverage=[oiNow!=null,fund!=null,d.imbalance!=null,flow!=null,spread!=null].filter(Boolean).length,corePrimary=core.filter(x=>String(x.source||'').startsWith('binance-futures')).length/core.length,maxLatency=Math.max(...[...core,oi,fr,book,bt].filter(Boolean).map(x=>x.latency||0),0),bonus=consensus?.state==='CONFIRMED'?8:consensus?.state==='DIVERGENT'?2:0,quality=Math.round(clamp(corePrimary*50+(coverage/5)*25+(maxLatency<=1500?17:maxLatency<=3000?12:maxLatency<=5500?6:1)+bonus)),oiContext=oi5==null||price5==null?'INSUFFICIENT':oi5>0&&price5>0?'UPSIDE PARTICIPATION':oi5>0&&price5<0?'DOWNSIDE PARTICIPATION':oi5<0?'DELEVERAGING':'FLAT';
const payload={symbol,observed_at:bucket,price,state:engine.state,evidence_score:engine.evidence_score,quality_score:quality,regime:engine.regime,mtf:engine.mtf,derivatives:{openInterest:oiNow,oi5,oi15,oi1h,funding:fund,markPrice:mark,price5,oiContext,consensus:consensus?{state:consensus.state,markSpreadBps:n(consensus.agreement?.markSpreadBps),fundingDiffBps:n(consensus.agreement?.fundingDiffBps),binance:consensus.venues?.binance||null,bybit:consensus.venues?.bybit||null}:null},orderflow:{depth:d.imbalance,bidNotional:d.bidNotional,askNotional:d.askNotional,taker:flow,spread,deviation},provenance:{collector:'server-v73',engine:'canonical-v73',dataClass:'futures-validated',ticker:tk.source,candles:[k5.source,k15.source,k1.source,k4.source],crossVenue:consensus?.state||'INSUFFICIENT',degraded:core.some(x=>x.degraded)||[oi,fr,book,bt].filter(Boolean).some(x=>x.degraded),maxLatencyMs:maxLatency}};
const saved=await db('tcc_observations?on_conflict=symbol,observed_at',{method:'POST',body:JSON.stringify(payload),prefer:'resolution=ignore-duplicates,return=representation'});return{symbol,stored:Array.isArray(saved.data)&&saved.data.length>0,deduped:Array.isArray(saved.data)&&saved.data.length===0,state:engine.state,evidence:engine.evidence_score,quality,regime:engine.regime,consensus:payload.derivatives.consensus?.state||'INSUFFICIENT',oiContext}}
module.exports=async function(req,res){Object.entries(H).forEach(([k,v])=>res.setHeader(k,v));res.setHeader('Cache-Control','no-store');if(!['GET','POST'].includes(req.method))return res.status(405).json({error:'Method not allowed'});if(!U()||!K())return res.status(200).json({configured:false});if(!(await authorized(req)))return res.status(401).json({error:'observer authorization required'});const startedAt=new Date(),started=Date.now(),requested=String(req.query?.symbol||'ALL').toUpperCase(),symbols=requested==='ALL'?SYMBOLS:SYMBOLS.includes(requested)?[requested]:[];if(!symbols.length)return res.status(400).json({error:'unsupported symbol',supported:SYMBOLS});const results=[];for(const s of symbols){try{results.push(await observe(s))}catch(e){results.push({symbol:s,error:e.message})}}const success=results.filter(x=>!x.error).length,run={started_at:startedAt.toISOString(),finished_at:new Date().toISOString(),collector:'server-v73',requested_symbol:requested,success_count:success,failure_count:results.length-success,duration_ms:Date.now()-started,results};await db('tcc_collector_runs',{method:'POST',body:JSON.stringify(run)}).catch(()=>null);return res.status(200).json({configured:true,collector:'server-v73',engine:'canonical-v73',supported:SYMBOLS,results})};